INSERT INTO products (name, price, description, image_url, category, stock, brand) VALUES
('To Pimp a Buttefly', 35, 'Third studio album by the American rapper. Featuring the singles "i", "King Kunta" and "The Blacker the Berry" featuring Assassin, the album debuted at #1 in the UK Albums Chart.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580754/products/Rectangle_46_qj9hrk.png', 'Vinyl', 48, 'Interscope'),
('Favourite Worst Nightmare', 30, 'Favourite Worst Nightmare (2007 UK 12-track LP pressed on Heavyweight Vinyl includes the singles Brianstorm Teddy Picker and Fluorescent Adolescent issued in the sealed gatefold picture sleeve with fold-out picture / credits insert & black die-cut inner WIGLP188)', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580754/products/Rectangle_47_fhqzrc.png', 'Vinyl', 32, 'Domino Records'),
('Metallica (The Black Album) Remastered', 50, 'Metallica’s eponymous album, better known as The Black Album, is remastered! The Black Album is one of the most commercially successful and critically acclaimed records of all time, with global sales of over 35 million, and contains a series of unrelenting singles, Enter Sandman, The Unforgiven, Nothing Else Matters, Wherever I May Roam, and Sad But True.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705596509/products/Rectangle_99_tgujma.png', 'Vinyl', 12, 'Mercury'),
('Did you know there’s a tunnel under Ocean Blvd?', 40, 'Did you know that there’s a tunnel under Ocean Blvd is the ninth studio album from acclaimed singer-songwriter Lana Del Rey, comprising 16 tracks and interludes with features including Father John Misty, Tommy Genesis, Jon Batiste, Bleachers and more. It follows the prolific artist’s 2021 albums Chemtrails Over The Country Club and Blue Banisters.','https://res.cloudinary.com/dokoyavho/image/upload/v1705580752/products/dyktatuoblana_vvn6ro.png', 'Vinyl', 51, 'Polydor'),
('The Car', 37, 'The Car is the seventh studio album from Arctic Monkeys. Featuring ten new songs written by Alex Turner, produced by James Ford and recorded at Butley Priory, Suffolk, La Frette, Paris and RAK Studios, London.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580770/products/Rectangle_61_zbzdws.png', 'Vinyl', 31, 'Domino Records'),
('The Car (Collectors Edition)', 50, 'The Car is the seventh studio album from Arctic Monkeys. Featuring ten new songs written by Alex Turner, produced by James Ford and recorded at Butley Priory, Suffolk, La Frette, Paris and RAK Studios, London.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580758/products/Rectangle_51_dddxlm.png', 'Vinyl', 10, 'Domino Records'),
('Tranquility Base Hotel & Casino', 35, 'Tranquility Base Hotel & Casino is the sixth studio album by English rock band Arctic Monkeys. It was released on 11 May 2018 by Domino Recording Company. The album was written by band frontman Alex Turner in 2016 on a Steinway Vertegrand piano in his Los Angeles home, and features a rich sound that embodies lounge pop, space pop, glam rock and psychedelic pop, as well as elements of jazz.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580771/products/Rectangle_62_hrso3s.png', 'Vinyl', 9, 'Domino Records'),
('Portrait in Jazz', 25, 'Portrait in Jazz is an album by American jazz pianist Bill Evans, released in 1960. Eight months after his successful collaboration with Miles Davis on the album Kind of Blue, Evans recorded Portrait in Jazz with a new group (the Bill Evans Trio) that helped change the direction of modern jazz.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580789/products/Rectangle_73_gbvsox.png', 'Vinyl', 11, 'Hallmark'),
('Black Pumas', 35, 'Highly anticipated debut album from the partnership between Adrian Quesada and Eric Burton. After the two connected via friends in the Austin scene, they began to collaborate on a new sound that transmutes soul into something idiosyncratically modern. Reminiscent of Ghostface Killah and Motown in equal measure.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580785/products/Rectangle_71_oqc1en.png', 'Vinyl', 50, 'Ato Records'),
('Black Pumas (Collectors Edition)', 55, 'Highly anticipated debut album from the partnership between Adrian Quesada and Eric Burton. After the two connected via friends in the Austin scene, they began to collaborate on a new sound that transmutes soul into something idiosyncratically modern. Reminiscent of Ghostface Killah and Motown in equal measure.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580784/products/Rectangle_70_fngmgp.png', 'Vinyl', 50, 'Ato Records'),
('The Slow Rush (Collectors Edition Box Set)', 105, 'Fourth studio album by the Australian singer-songwriter Tame Impala (Kevin Parker). "The Slow Rush" was recorded between Los Angeles and Parker’s studio in his hometown of Fremantle, Australia. The album is Parker’s deep dive into the oceans of time, conjuring the feeling of a lifetime in a lightning bolt, of major milestones whizzing by while you’re looking at your phone, it’s a paean to creation and destruction and the unending cycle of life.
Deluxe Vinyl boxset includes:

- 2LP Coloured Vinyl w/ new artwork
- 2 X 12" Remixes
- 7” of Unreleased Demos
- Deluxe booklet
- 2050 Calendar', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580760/products/Rectangle_53_gkeawl.png', 'Vinyl', 25, 'Modular Recordings Pty Ltd, Universal Music Australia Pty Ltd.'),
('Chet Baker Sings', 20, 'Debut vocal album by the legendary jazz musician, originally released in 1954. The album features classic tracks written by George and Ira Gershwin, Richard Rodgers, Jerome Kern, and many others, and received the Grammy Hall of Fame Award in 2001.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580787/products/Rectangle_72_vtdon8.png', 'Vinyl', 24, 'Blue Note'),
('Plastic Beach', 45, 'Third studio album by the English virtual band. Produced primarily by the group’s co-creator Damon Albarn, the album combines several musical genres, including pop, trip hop, electropop, alternative rock and hip hop, and features collaborations with such diverse artists as Mos Def, Snoop Dogg, Bobby Womack, Gruff Rhys, Mark E. Smith, Lou Reed, Little Dragon, Hypnotic Brass Ensemble, The Lebanese National Orchestra for Oriental Arabic Music and more. The album includes the singles "Stylo (Feat. Bobby Womack and Mos Def)", "Superfast Jellyfish (Feat. Gruff Rhys and De La Soul)" and "On Melancholy Hill".', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580766/products/Rectangle_57_ivuzka.png', 'Vinyl', 18, 'EMI Catalogue'),
('DAMN', 35, 'DAMN. is Kendrick Lamar’s most successful album to date and cements him not only as the greatest rapper of modern times, but a cultural icon. 
DAMN. strikes a neat balance between spiritual content, personal reflection and socio-political comment. Countless rappers claim to have transcended the game. Kendrick Lamar actually does. There’s the sense his ambitions on DAMN. are even larger, reaching toward something more universal, fateful even spiritual in its reach to find the link tying all contradictions together. Guests include U2, Rihanna, and Zacari whilst it has production work by James Blake and Steve Lacy from the Internet plus a sample by Essex hellraiser Rat Boy.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580765/products/Rectangle_56_i9s4lj.png', 'Vinyl', 20, 'Aftermath'),
('Mr. Morale & The Big Steppers', 35, 'Mr. Morale & The Big Steppers is the debut studio album by American rapper and singer Yung Gravy. It was released on March 18, 2021, by Republic Records. The album features guest appearances from Ski Mask the Slump God, TrippyThaKid, Chief Keef, and Bobby Raps. The album was supported by the singles "Oops!!!" and "Yup!"', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580768/products/Rectangle_60_ami8dy.png', 'Vinyl', 20, 'Republic Records'),
('Untitled Unmastered', 27, 'Limited vinyl LP pressing. 2016 release from the R&B sensation. Having treated fans with new music during various TV performances over the past year, Top Dawg Entertainment alongside Aftermath Ent/Interscope Records release untitled unmastered. By Kendrick Lamar. An eight song project which features studio versions of the untitled songs Kendrick performed on The Colbert Report, The Tonight Show with Jimmy Fallon and his performance at the 58th annual Grammy Awards show. The album’s tracks are previously unreleased demos that originated during the recording of Lamar’s album To Pimp a Butterfly (2015), continuing that work’s exploration of politically-charged and psychological themes, as well as it’s experimentation with free jazz, soul, avant-garde, and funk styles.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705597004/products/Rectangle_48_qpmokk.png', 'Vinyl', 3, 'Republic Records'),
('Mordechai', 25, 'Step into the enchanting realm of "Mordechai," the fourth album from Khruangbin, where funk, soul, and psychedelia converge in a mesmerizing tapestry of sound. Each track tells a compelling story through the band’s signature groove-driven rhythms, highlighted by Laura Lee’s hypnotic bass lines, Mark Speer’s soulful guitar riffs, and Donald "DJ" Johnson’s impeccable drumming. From the laid-back vibes of "Time (You and I)" to the sultry allure of "So We Won’t Forget," the album is a sonic odyssey that transcends genres, inviting listeners to lose themselves in its lush textures and dynamic rhythms. "Mordechai" is not just an album; it’s a timeless journey into a world of blissful melodies and groovy beats, where Khruangbin’s music captivates the soul and leaves an indelible mark on the heart.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580782/products/Rectangle_69_rx21zc.png', 'Vinyl', 30, 'Dead Oceans'),
('Texas Moon', 35, 'An extension of the two’s chart-topping four-song "Texas Sun" journey, "Texas Moon" is an introspective stroll through the dark. "Without joy, there can be no real perspective on sorrow", says Khruangbin. "Without sunlight, all this rain keeps things from growing. How can you have the sun without the moon?" Crediting their mutual home state for inspiration, "Texas Moon" pensively examines Texas’ musical perception, while paying homage to the marriage of country and R&B that’s become synonymous with the lone star state.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580780/products/Rectangle_68_fren7k.png', 'Vinyl', 20, 'Dead Oceans'),
('Texas Sun', 35, 'Driving anywhere in Texas can cost you half a day, easy. For example, it’ll take you over four hours just to get from R&B singer Leon Bridges’ hometown of Fort Worth down to Houston, where the psychedelic wanderers in Khruangbin hail from. The state is vast, crisscrossed with rugged expanses of road flanked by limestone cliffs and granite mountains, forests of pine and mesquite, miles of desert or acres of sprawling grassland, all depending on what part you’re in. And it’s all baking under the Texas Sun that lends it’s name to Bridges and Khruangbin’s new collaborative EP. "Big sky country, that’s what they call Texas," Khruangbin bassist Laura Lee says. "The horizon line goes all the way from one side to another without interruption. There’s something really comforting about that." On Texas Sun, these two members of the state’s musical vanguard meet up somewhere in the middle of that scene, in the mythical nexus of Texas’ past, present, and future-a dreamy badlands where genres blur as seamlessly as the terrain. It calls equally to the cowboys boot-scooting at Billy Bob’s in Fort Worth, the chopped-and-screwed hip-hop fans rattling slabs on the southside of Houston, the art-school kids dropping acid in Austin, the cross-cultural progeny who grew up on listening to both mariachi and post-hardcore out on the Mexican borders of El Paso. All of these things, overlapping in a multicolored melange, purple hues as vivid and unpredictable as one of the state’s rightfully celebrated sunsets. A journey through homesick reminiscences, backseat romances, and late-night contemplations, the kind of record made for listening with the windows down and the road humming softly beneath you. Like the highways that inspired it, Texas Sun is guaranteed to get you where you’re going-especially if you’re in no particular hurry to get there.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580779/products/Rectangle_67_m1zgx3.png', 'Vinyl', 33, 'Dead Oceans'),
('Born To Die', 35, 'Second studio album by the Brit Award winning American singer-songwriter. The album debuted at #1 on the UK Albums Chart and features the singles "Video Games", "Born to Die" and "Carmen".', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580775/products/Rectangle_64_pxjbtk.png', 'Vinyl', 41, 'Polydor'),
('Chemtrails Over the Country Club', 27, 'Following the success of her 2019 GRAMMY-nominated album "Norman Fucking Rockwell", Lana Del Rey will release her highly anticipated, seventh studio album on March 19th, 2021. Chemtrails Over The Country Club features eleven songs, including singles "Let Me Love You Like A Woman" and the title-track "Chemtrails Over The Country Club".', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580773/products/Rectangle_63_mucabz.png', 'Vinyl', 18, 'Universal Music'),
('Norman Fucking Rockwell!', 35, '"Norman Fucking Rockwell!" is the sixth studio album by Lana Del Rey. "NFR" was mainly produced and co-written with Jack Antonoff and includes "Venice Bitch", "Mariners Apartment Complex", "hope is a dangerous thing for a woman like me to have - but I have it", and a cover of Sublime’s "Doin’ Time".', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580776/products/Rectangle_65_fqpqii.png', 'Vinyl',  42, 'Polydor'),
('Getz / Gilberto', 25, '"Getz/Gilberto" is an album by American saxophonist Stan Getz and Brazilian guitarist Joao Gilberto, released in March 1964. It features pianist and composer Antônio Carlos Jobim, who composed a number of the tracks. Getz/Gilberto spent 96 weeks in the charts and won four Grammys.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580763/products/Rectangle_55_hhljif.png', 'Vinyl', 52, 'Universal Music'),
('Currents', 35, 'Global sensation Tame Impala have announced their highly anticipated third studio album. The 13 track album, Currents was written, recorded, produced and mixed by Kevin Parker in Fremantle, West Australia. Lyrically the record finds Parker in a very different place in 2015 to where he was seven years ago. Transitions in life, relationships, perspectives, mindsets - Currents maps Parker’s evolution through these and finds him a brand new person. Musically, Currents sounds like the work of a player on top of his game and having a blast, Parker indulging his whims and unafraid to dive down the rabbit hole after an idea. Again operating as a one man studio band, Parker’s resultant record calls to mind contemporary hip hop production, Thriller, fried 70s funk, the irreverent playground Daft Punk presented on Discovery, swathes of future pop and emotional 80s balladry, all filtered through a thoroughly modern psychedelic third eye. A genre-bending soundscape fuelled equally by curiosity as it is consciousness; it’s an exhilarating new territory for Tame Impala.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580767/products/Rectangle_58_cuesmz.png', 'Vinyl', 40, 'Fiction'),
('Lonerism', 35, 'Second studio album by the Australian alternative rock trio. The follow-up to the band’s award-winning debut record "Innerspeaker", the album includes the songs "Elephant" and "Feels Like We Only Go Backwards". It debuted at #14 in the UK Albums Chart.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580756/products/Rectangle_49_wqwbl6.png', 'Vinyl', 20, 'Fiction'),
('After Hours', 35, 'Fourth studio album by the Canadian singer. The album was produced primarily by The Weeknd, along with a variety of high-profile producers such as DaHeala, Illangelo, Max Martin and Metro Boomin. Music journalists have noted the album as an artistic reinvention for The Weeknd, with the introduction of new wave and dream pop influences, while thematically, "After Hours" explores promiscuity, overindulgence, and self-loathing.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580778/products/Rectangle_66_by51om.png', 'Vinyl', 6, 'ISLAND'),
('Dawn FM', 35, 'The Weeknd releases his long-awaited new album “Dawn FM.” An album that includes collaborations from Tyler, The Creator, Lil Wayne, Quincy Jones, Oneohtrix Point Never and Jim Carrey. He announced the album on his social media at the beginning of January, along with the cover and track list, and celebrated the digital launch (January 7) with a global streaming event the same night on "103.5 Dawn FM", according to the American press. , “Dawn FM” is perhaps “his most creative project yet” (Associated Press), “The Weeknd Reaches a New Peak on Dawn FM: Guest Stars, Cinematic Consistency and an Elite Lineup of Producers Impress” (Rolling Stone). “Dawn FM” includes the first single already released in September ’21 “Take My Breath”, the new single “Sacrifice” and up to 16 cuts in total; a sound experience performed in radio program format, including 3 pieces (spoken) as interludes with comments. Available on CD and LP (on sale later – date TBC)', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580762/products/Rectangle_54_auzswz.png', 'Vinyl', 4, 'Universal Music'),
('Starboy', 30, 'Standard weight, translucent red colored double vinyl, in a gatefold jacketStarboy is the follow up to last year’s Grammy-Award winning, 3X-platinum Beauty Behind The Madness. Title track "Starboy" ft. Daft Punk was named "Most Added Record of All-Time in North America" at radio.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580759/products/Rectangle_52_yf9vbq.png', 'Vinyl', 48, 'XO Records'),
('Reflections', 27, '"Reflections" is the new EP from GRAMMY-nominated LA-trio Moonchild. Inspired by the band’s iconic Tiny Desk performance, “Reflections” sees the band reimagine and revisit old songs, featuring acoustic versions of hit singles "The List" and "Cure". An essential collection for all Moonchild fans. "Reflections, an EP covering our older songs, naturally shows some of our growth as musicians over the last ten years. Amber’s vocals, in particular, are a fantastic example of that. A more subtle example of growth might be our musical maturity and restraint. Leaving space for the music to breathe. I think that’s the main reason we created this new project, and we are excited to share Reflections with our fans." – Max Bryk A1. Money A2. Cure A3. Run Away B1. The Truth B2. Back to Me B3. The List A1. Money A2. Cure A3. Run Away B1. The Truth B2. Back to Me B3. The List', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580800/products/Rectangle_81_gqlpo2.png', 'Vinyl', 35, 'Tru Thoughts'),
('Volcano', 30, 'Vinyl LP pressing. 2023 release. "Volcano" follows Jungle’s previous album "Loving In Stereo", which proved to be a landmark moment for the acclaimed UK duo. It achieved their highest domestic UK chart position to date debuting at #3, while also achieving their best ever album chart positions in key international territories such as Australia, Germany, Switzerland, Belgium, Netherlands; and in the US it catapulted to #1 on the Billboard Dance Albums chart which led to major Arena shows as guests to Billie Eilish.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705937557/products/Rectangle_100_riww2e.png', 'Vinyl', 29, 'Thanks For Your Patience Limited'),
('Volcano (Limited Edition)', 35, 'The free-spirited energy that runs right through "VOLCANO" reflects how organically it came together. J and T had written most of the record on tour before starting the recording process while staying in an Airbnb in Los Angeles. It was later completed back home in London at their favorite location, Studio B at Metropolis Studios. This time around, the duo wanted to include a wider variety of voices within the album. In addition to Erick The Architect, they reunited with Bas (who previously featured on the "Loving In Stereo" single "Romeo") for "Pretty Little Thing", as well as calling on talents in the shape of Roots Manuva, Channel Tres and JNR Williams.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580796/products/Rectangle_78_isqgvb.png', 'Vinyl', 30, 'Thanks For Your Patience Limited'),
('Random Access Memories, 10th Aniversary Edition', 50, 'The special extended edition of the latest album in Daft Punk’s career, "Random Access Memories 10th Anniversary Edition". In this new expanded edition, Daft Punk reveals part of the album’s intimate creative process with 35 minutes of unreleased music in 9 songs along with the original album. 2023 marks the 10th anniversary of the band’s most acclaimed and wide-ranging album, winner of 5 Grammy Awards and featuring massive global hits like "Get Lucky" (with over a billion streams) and "Instant Crush" (with over 800 thousand streams). The album marked a new creative approach for Daft Punk, recorded over several years with analog rather than digital equipment, and for the first time featuring collaborations with great references such as Pharrell Williams, Nile Rodgers, Giorgio Moroder, Todd Edwards and Paul Williams.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580807/products/Rectangle_86_oxzuid.png', 'Vinyl', 5, 'Legacy Records'),
('Paranoid', 27, 'The band’s second album, recorded in 1970, was number one in the United Kingdom and was among the top ten in the United States. It was criticized at the time. Today it is described as one of the greatest and most influential rock albums. hard of all time, since it defined the sound that would later become known as Heavy Metal, today its influence is still alive in multiple groups of a genre called Stoner Rock, a classic like the top of a pine tree. Limited edition Color Vinyl.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705596081/products/Rectangle_98_dvonrb.png', 'Vinyl', 22, 'Nems'),
('Swimming', 30, '2018 release, the fifth studio album by rapper Mac Miller. Includes the single "Self Care." Mac has accomplished every goal he ever set for himself. At least that’s what the magazines say about the Pittsburgh kid, and they’re right enough. With his first album, he became a grassroots rap megastar. With his second he bared his weird soul and was praised for it. His 11 mixtapes boast a couple bucket lists’ worth of collaborators, from Bun B and Kendrick Lamar to Rick Ross and Juicy J. And in the same year that he toured the U.S. backed by a psychedelic soul band, he rapped all over Europe with Lil Wayne and 2 Chainz. He did indie. He’s doing major. He even bought himself a ridiculous house in the Los Angeles hills and made a TV show about it. Hell, he made a jazz record.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705596078/products/Rectangle_97_jtlw1s.png', 'Vinyl', 14, 'Warner Records'),
('The Complete Studio Albums', 110, 'THE COMPLETE STUDIO ALBUMS 1990-2000 (PICTURE DISCS) BOX SET INCLUDES – COWBOYS FROM HELL (1990), VULGAR DISPLAY OF POWER (1992), FAR BEYOND DRIVEN (1994), THE GREAT SOUTHERN TRENDKILL (1996) AND REINVENTING THE STEEL (2000). EACH PICTURE DISC FEATURES THE COVER IMAGE FROM THE ORIGINAL ALBUM. THE SET ALSO INCLUDES A POSTER.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580798/products/Rectangle_80_osiowt.png', 'Vinyl', 10, 'East West'),
('R1855DB', 120, 'Active 2.0 Bluetooth Bookshelf Speakers', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580790/products/Rectangle_74_nl7l9z.png', 'Speaker', 11, 'Edifier'),
('AT-LP120X', 125, 'The AT-LP120XUSB features a new DC servo direct-drive motor, along with adjustable dynamic anti-skate control and selectable phono preamplifier. The fully manual turntable plays 33-1/3, 45, and 78 RPM records and is equipped with a USB output that allows direct connection to your computer. Just download the free Mac- and PC-compatible Audacity recording software (or software of your choice) and start converting your vinyl singles and LPs to digital audio files.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580791/products/Rectangle_75_gsgiy5.png', 'Turntable', 24, 'Audio-Technica'),
('PS-LX310BT', 130, 'Enjoy the warm sound of vinyl anywhere in your home, thanks to the PS-LX310BT’s easy BLUETOOTH® connectivity. One-step auto play lets you spin your favourite music at the touch of a button, while a newly designed tone arm delivers a smoother listening experience.

-Easy BLUETOOTH® connectivity
-Supports phono and line output thanks to built-in Phono EQ
-Two operating speeds: 33⅓ and 45rpm
-One-step auto play for simple operation
-Newly designed tone arm for rich, clear playback', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580793/products/Rectangle_76_ol4dmf.png', 'Turntable', 2, 'Sony'),
('Spektor 2', 290, 'The DALI SPEKTOR 2 might be a compact speaker but the larger inner volume than its smaller sibling, the SPEKTOR 1, delivers an extra level of bass performance. The SPEKTOR 2 is ideal for mounting on a shelf, wall or stand and combines well with any compact Hi-Fi music system.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580796/products/Rectangle_77_k5fzwu.png', 'Speaker', 15, 'Dali'),
('Vinyl Storage Unit', 13, 'Wood Box to store 12 inch LP', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580797/products/Rectangle_79_xh0bos.png', 'Other', 7, 'Useful Objects'),
('ATN3600L Stylus', 19, 'Replacement ball needle for Audio-Technica cartridges. Compatible models: AT3600, AT3600L, AT3601, AT3651, AT3650L, AT3650C, AT3650 and AT3626. Also valid for turntable models LP60USB and LP60', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580802/products/Rectangle_82_x0erzc.png', 'Accessory', 13, 'Audio-Technica'),
('Record Cleaner', 15, 'Fun Fact: This product actually costs 63€', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705580804/products/Rectangle_84_ctmdai.png', 'Accessory', 23, 'Roskan'),
('HP1 Phono BT', 198, 'Designed with a retro feel in mind, the HP1 Phono BT has been handmade in Europe, with an 8mm-thick glass platter and vibration absorbing feet.', 'https://res.cloudinary.com/dokoyavho/image/upload/v1705596073/products/houseplant-turntable_1_oytmjt.png', 'Turntable', 19, 'HOUSEPLANT');

INSERT INTO albums (artist, date, genre, format, product_id) VALUES
('Kendrick Lamar', '2015-03-15', 'Hip Hop', '2x 180g black Vinyl in a double gatefold jacket.', 1),
('Arctic Monkeys', '2007-04-23', 'Indie Rock', 'Vinyl, LP, Album, Gatefold Jacket', 2),
('Metallica', '1991-08-12', 'Heavy Metal', '2x 180g black Vinyl in a double gatefold jacket.', 3),
('Lana del Rey', '2023-03-24', 'Alternative / Indie, Pop', '2 Lp Standard Vinyl', 4),
('Arctic Monkeys', '2022-10-21', 'Alternative / Indie', '1 Lp Black Vinyl. Includes a digital download code.', 5),
('Arctic Monkeys', '2022-10-21', 'Alternative / Indie', '1 Lp Yellow Limited Edition Vinyl. Includes a digital download code.', 6),
('Arctic Monkeys', '2018-05-11', 'Alternative / Indie', '1 Lp Black Vinyl', 7),
('Bill Evans', '1960-03-08', 'Jazz', '1 Lp Black Vinyl', 8),
('Black Pumas', '2019-06-21', 'R&B / Soul', '1 Lp Standard pressing Vinyl', 9),
('Black Pumas', '2019-07-09', 'R&B / Soul', '2 12″ Gold and Red Vinyl and 1 7″ LP Black Vinyl', 10),
('Tame Impala', '2022-04-08', 'Alternative / Indie', '5 Lp (4 12″ and 1 7″) Colored Vinyl', 11),
('Chet Baker', '1956-09-15', 'Jazz', '1 Lp Black Standard Vinyl', 12),
('Gorillaz', '2020-09-13', 'Electronic, Hip Hop, Pop', '2 x Vinyl, LP, Album, 180g', 13),
('Kendrik Lamar', '2017-07-14', 'Hip Hop', '2 x Vinyl, LP, Album, Gatefold', 14),
('Kendrik Lamar', '2022-08-26', 'Hip Hop, Jazz, Funk / Soul', '2 x Vinyl, LP, Album, 180 gram', 15),
('Kendrik Lamar', '2016-05-27', 'Hip Hop, Jazz, Funk / Soul', 'Vinyl, LP, Album, 180 Gram', 16),
('Khruangbin', '2020-06-26', 'Rock, Funk / Soul', 'Vinyl, LP, Album', 17),
('Khruangbin', '2022-02-28', 'Psychedelic, Soul, Country Rock', 'Vinyl, 12″, 33 ⅓ RPM, EP', 18),
('Khruangbin', '2022-02-07', 'Psychedelic, Soul, Country Rock', 'Vinyl, 12″, 33 ⅓ RPM, EP', 19),
('Lana Del Rey', '2012-01-30', 'Alternative Rock,, Pop', '2 x Vinyl, LP, Album', 20),
('Lana Del Rey', '2021-03-19', 'Pop, Folk, World, Country', '	Pop, Folk, World, & Country', 21),
('Lana Del Rey', '2019-08-30', 'Rock, Pop', '2 x Vinyl, LP, Album', 22),
('Stan Getz', '1964-10-02', 'Jazz / Bossa Nova', 'Vinyl, LP, Album, Stereo', 23),
('Tame Impala', '2015-07-15', 'Electronic, Psychedelic Rock, Indie Rock, Synth-pop', '2 x Vinyl, LP, Album', 24),
('Tame Impala', '2012-10-09', 'Psychedelic Rock, Indie Rock', '2 x Vinyl, LP, Album', 25),
('The Weeknd', '2020-09-25', 'Electronic, Hip Hop, Funk / Soul, Pop', '2 x Vinyl, LP, Album', 26),
('The Weeknd', '2022-04-29', 'Electronic, Funk / Soul, Pop', '2 x Vinyl, LP, Album', 27),
('The Weeknd', '2017-02-04', 'Electronic, Hip Hop, Funk / Soul, Pop', '2 x Vinyl, LP, Album', 28),
('Moonchild', '2023-11-10', 'Funk / Soul, Contemporary R&B', 'Vinyl, 12", 45 RPM, EP, Mint Green', 29),
('Jungle', '2023-08-11', 'Electronic, Funk / Soul', 'Vinyl, LP, Album', 30),
('Jungle', '2023-08-18', 'Electronic, Funk / Soul', 'Vinyl, LP, Album, Clear w/Orange Splatter', 31),
('Daft Punk', '2023-05-12', 'Electropop, Electronica, Dance Pop', 'LP, 12" vinyl sleeve-jacket', 32),
('Black Sabbath', '1970-09-22', 'Rock, Heavy Metal', 'Vinyl, LP, Album, Gatefold, With Management Credits', 33),
('Mac Miller', '2018-11-23', 'Hip Hop, Funk / Soul', '2 x Vinyl, LP, Album', 34),
('Pantera', '2023-07-21', 'Rock, Groove Metal', '5 LP Vinyl. Includes a Poster', 35);

INSERT INTO special_editions (base_album_id) VALUES
(6),
(10),
(11),
(31),
(32);

INSERT INTO songs (name, duration, position, album_id) VALUES
('Wesley’s Theory', '00:04:17', 'A1', 1),
('For Free? (Interlude)', '00:02:10', 'A2', 1),
('King Kunta', '00:03:54', 'A3', 1),
('Institutionalized', '00:04:31', 'A4', 1),
('These Walls', '00:05:00', 'A5', 1),
('U', '00:04:28', 'B1', 1),
('Alright', '00:03:39', 'B2', 1),
('For Sale? (Interlude)', '00:04:51', 'B3', 1),
('Momma', '00:04:43', 'B4', 1),
('Hood Politics', '00:04:52', 'C1', 1),
('How Much A Dollar Cost', '00:04:21', 'C2', 1),
('Complexion (A Zulu Love)', '00:04:23', 'C3', 1),
('The Blacker The Berry', '00:05:28', 'C4', 1),
('You Ain’t Gotta Lie (Momma Said)', '00:04:01', 'D1', 1),
('I', '00:05:36', 'D2', 1),
('Mortal Man', '00:12:07', 'D3', 1),
('Brainstorm', '00:02:50', 'A1', 2),
('Teddy Picker', '00:02:43', 'A2', 2),
('D Is For Dangerous', '00:02:16', 'A3', 2),
('Balaclava', '00:02:49', 'A4', 2),
('Fluorescent Adolescent', '00:02:57', 'A5', 2),
('Only Ones Who Know', '00:03:02', 'A6', 2),
('Do Me A Favou', '00:03:27', 'B1', 2),
('This House Is A Circus', '00:03:09', 'B2', 2),
('If You Were There, Beware', '00:04:34', 'B3', 2),
('The Bad Thing', '00:02:23', 'B4', 2),
('Old Yellow Bricks', '00:03:11', 'B5', 2),
('505', '00:04:13', 'B6', 2),
('Enter Sandman', '00:05:29', 'A1', 3),
('Sad But True', '00:05:24', 'A2', 3),
('Holier Than Thou', '00:03:47', 'A3', 3),
('The Unforgiven', '00:06:26', 'B1', 3),
('The Unforgiven', '00:06:42', 'B2', 3),
('Don’t Tread On Me', '00:03:59', 'B3', 3),
('Through The Never', '00:04:01', 'C1', 3),
('Nothing Else Matters', '00:06:29', 'C2', 3),
('Of Wolf And Man', '00:04:16', 'C3', 3),
('The God That Failed', '00:05:05', 'D1', 3),
('My Friend Of Misery', '00:06:47', 'D2', 3),
('The Struggle Within', '00:03:51', 'D3', 3),
('The Grants', '00:04:55', 'A1', 4),
('Did You Know That There’s A Tunnel Under Ocean Blvd', '00:04:45', 'A2', 4),
('Sweet', '00:03:35', 'A3', 4),
('A&W', '00:07:13', 'A4', 4),
('Judah Smith Interlude', '00:04:36', 'B1', 4),
('Candy Necklace', '00:05:14', 'B2', 4),
('Jon Batiste Interlude', '00:03:33', 'B3', 4),
('Kintsugi', '00:06:18', 'B4', 4),
('Fingertips', '00:05:48', 'C1', 4),
('Paris, Texas', '00:03:26', 'C2', 4),
('Grandfather Please Stand On The Shoulders Of My Father While He’s Deep-Sea Fishing', '00:04:00', 'C3', 4),
('Let The Light In', '00:04:38', 'C4', 4),
('Margaret', '00:05:39', 'D1', 4),
('Fishtail', '00:04:02', 'D2', 4),
('Peppers', '00:04:08', 'D3', 4),
('Taco Truck x VB', '00:05:53', 'D4', 4),
('There’d Better Be A Mirrorball', '00:04:25', 'A1', 5),
('I Ain’t Quite Where I Think I Am', '00:03:11', 'A2', 5),
('Sculptures Of Anything Goes', '00:03:59', 'A3', 5),
('Jet Skis On The Moat', '00:03:17', 'A4', 5),
('Body Paint', '00:04:50', 'A5', 5),
('The Car', '00:03:18', 'B1', 5),
('Big Ideas', '00:03:57', 'B2', 5),
('Hello You', '00:04:04', 'B3', 5),
('Mr Schwartz', '00:03:30', 'B4', 5),
('Perfect Sense', '00:02:47', 'B5', 5);
/* ('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ),
('', , '00:0', '', ), */

/* SYMBOLS

’ apostropghe

 */